import "../styles/PostPage.css";
import { IoClose } from "react-icons/io5";
import { Link } from "react-router-dom";
export const PostPage = () => {
	return (
		<div className="postPage">
			<Link className="postCloseButton" to={"/home"}>
				<IoClose />
			</Link>
			<div className="postTitleDiv">
				<h1>Vest 1</h1>
				<p>Author: Ja</p>
			</div>
			<div className="postDescDiv">
				<p className="postDescText">
					BLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBABLABLALBLBALBALBLBALBALBALBALBALBLBA
				</p>
			</div>
		</div>
	);
};
